#:kivy 2.2.1

<CustomSlider>:

    # Background
    canvas.before:
        Color:
            rgba: self.background_color
        RoundedRectangle:
            pos:(0,0)
            size:self.size
            radius:[20,]

    # Slider
    Slider:
        id: my_slider
        value: root.value
        min: 0
        max: 1
        size_hint: (0.8, 1)
        pos_hint: {"center_x": 0.5, "center_y": 0.5}
