#:kivy 2.1.0

<ImprovedScreen>:

    Image:
        id: back_image
        source: root.back_image_path
        size_hint: None,None
        width: root.back_image_width
        height: root.back_image_height
        disabled: root.back_image_disabled
        opacity: root.back_image_opacity
        pos_hint: {"center_x":0.5,"center_y":0.5}
        allow_stretch: True
        keep_ratio: True
        anim_delay: 0.0166